import { StyleSheet, Platform } from "react-native";


const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: "#fff",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: Platform.OS === "ios" ? 8 : 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
      backgroundColor: "#fff",
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      alignContent: "center",
      color: "#00c5e3",
    },
    headerRight: {
      flexDirection: "row",
    },
    headerButton: {
      marginLeft: 16,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#f5f5f5",
      marginHorizontal: 16,
      marginVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 10,
      height: 40,
      borderWidth: 1,
      borderColor: "#e0e0e0",
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      height: 40,
      fontSize: 16,
      color: "#333",
    },
    container: {
      flex: 1,
      backgroundColor: "#fff",
    },
    listContent: {
      padding: 10,
      flexGrow: 1,
    },
    emptyListContent: {
      flexGrow: 1,
      justifyContent: "center",
    },
    conversationItem: {
      flexDirection: "row",
      padding: 14,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
      alignItems: "center",
      backgroundColor: "#fff",
    },
    conversationContent: {
      flexDirection: "row",
      flex: 1,
    },
    conversationImage: {
      width: 50,
      height: 50,
      borderRadius: 25,
      marginRight: 14,
      borderWidth: 2,
      borderColor: "#00c5e3",
    },
    conversationDetails: {
      flex: 1,
      justifyContent: "center",
    },
    conversationName: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 4,
    },
    conversationLastMessage: {
      fontSize: 14,
      color: "#666",
      marginBottom: 2,
    },
    conversationTimestamp: {
      fontSize: 12,
      color: "#00c5e3",
      alignSelf: "flex-end",
    },
    actionButtons: {
      flexDirection: "row",
      alignItems: "center",
    },
    actionButton: {
      padding: 8,
      marginLeft: 4,
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      width: "85%",
      backgroundColor: "#fff",
      padding: 20,
      borderRadius: 16,
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    largeModalContent: {
      height: "70%",
      width: "90%",
      justifyContent: "flex-start",
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 16,
      color: "#00c5e3",
      alignSelf: "flex-start",
    },
    modalText: {
      textAlign: "center",
      marginBottom: 20,
      color: "#333",
      lineHeight: 20,
    },
    input: {
      width: "100%",
      height: 50,
      borderColor: "#ddd",
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 15,
      marginBottom: 20,
      fontSize: 16,
      backgroundColor: "#f9f9f9",
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
    },
    modalButton: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      flex: 1,
      marginHorizontal: 5,
    },
    confirmButton: {
      backgroundColor: "#00c5e3",
    },
    cancelButton: {
      backgroundColor: "#f0f0f0",
    },
    deleteButton: {
      backgroundColor: "#FF3B30",
    },
    disabledButton: {
      backgroundColor: "#b7e5ee",
      opacity: 0.7,
    },
    buttonText: {
      color: "#333",
      fontWeight: "600",
      fontSize: 16,
    },
    buttonTextWhite: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    newConversationButton: {
      position: "absolute",
      bottom: 20,
      right: 20,
      backgroundColor: "#00c5e3",
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 5,
    },
    userItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#ccc",
      backgroundColor: "#fff",
    },
    userAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
      borderWidth: 2,
      borderColor: "#e0e0e0",
    },
    username: {
      fontSize: 16,
      color: "#333",
      flex: 1,
      marginLeft: 8,
      fontWeight: "500",
    },
    checkIcon: {
      marginLeft: 10,
    },
    selectedUserItem: {
      width: "100%",
      backgroundColor: "rgba(0, 197, 227, 0.1)",
    },
    searchUserContainer: {
      flexDirection: "row",
      width: "100%",
      marginBottom: 10,
    },
    searchUserInput: {
      flex: 1,
      height: 50,
      borderColor: "#ddd",
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 15,
      fontSize: 16,
      backgroundColor: "#f9f9f9",
      marginRight: 8,
    },
    searchButton: {
      width: 50,
      height: 50,
      backgroundColor: "#00c5e3",
      borderRadius: 10,
      justifyContent: "center",
      alignItems: "center",
    },
    userListContent: {
      width: "100%",
      flexGrow: 1,
    },
    modalActionsContainer: {
      width: "100%",
      flexDirection: "column",
      marginTop: 15,
    },
    cancelActionButton: {
      backgroundColor: "#f0f0f0",
      paddingVertical: 14,
      borderRadius: 10,
      marginBottom: 10,
      alignItems: "center",
    },
    createActionButton: {
      backgroundColor: "#00c5e3",
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: "center",
    },
    cancelActionText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#333",
    },
    createActionText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#fff",
    },
    // Loading styles
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#fff",
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
      color: "#8e8e93",
    },
    // Error styles
    errorContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
      backgroundColor: "#fff",
    },
    errorTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#333",
      marginTop: 16,
      marginBottom: 8,
    },
    errorMessage: {
      fontSize: 16,
      color: "#666",
      textAlign: "center",
      marginBottom: 24,
    },
    retryButton: {
      backgroundColor: "#00c5e3",
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    retryButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    // Empty state styles
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 50,
      paddingHorizontal: 20,
    },
    emptyText: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#8e8e93",
      marginTop: 16,
    },
    emptySubText: {
      fontSize: 14,
      color: "#8e8e93",
      textAlign: "center",
      marginTop: 8,
    },
    emptySearchContainer: {
      padding: 30,
      alignItems: "center",
      justifyContent: "center",
    },
    emptySearchText: {
      fontSize: 14,
      color: "#8e8e93",
      textAlign: "center",
    },
    // Error banner styles
    errorBanner: {
      backgroundColor: "#FF3B30",
      padding: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    errorBannerContent: {
      flexDirection: "row",
      alignItems: "center",
    },
    errorBannerIcon: {
      marginRight: 10,
    },
    errorBannerText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "600",
    },
    errorBannerAction: {
      color: "#fff",
      fontSize: 14,
      opacity: 0.8,
      fontWeight: "500",
    },
  });

export default styles;